Check Tests
AFH7233/sky-touch-test pull request #3
Opened 2018-09-24 16:48 UTC by AFH7233

2018-09-24 22:24 UTC, grunger94 requested changes

2018-09-24 22:24 UTC, grunger94 commented on product-crud/src/test/java/com/afh/skytouch/services/product/queue/producers/FindAllMessageSenderTest.java
> +import static org.junit.Assert.*;
Avoid using wildcard imports

2018-09-24 22:24 UTC, grunger94 commented on commons-library/pom.xml
> -            <version>${lombok.version}</version>
Why were these versions brought back?

2018-09-24 22:24 UTC, grunger94 commented on docker/docker-compose.yml
> +      - "5672:5672"
The default port should be overridden

2018-09-24 22:24 UTC, grunger94 commented on commons-library/pom.xml
> +            <groupId>org.jetbrains</groupId>
Did these dependencies sneak in by mistake?

2018-09-24 22:24 UTC, grunger94 commented on management-api/src/main/java/com/afh/skytouch/managment/controllers/GenericProductController.java
> +    public static final String PRODUCT_ATRIBUTE_NAME = "product";
Could these constants be private?

2018-09-24 22:24 UTC, grunger94 commented on management-api/src/main/java/com/afh/skytouch/managment/controllers/GenericProductController.java
> +    @Value("${managment.service.timeout}")
Typo in management?

2018-09-24 22:24 UTC, grunger94 commented on management-api/src/main/java/com/afh/skytouch/managment/controllers/GenericProductController.java
> +        System.out.println("Checking again: " + id);
Remove any prints left behind

2018-09-24 22:24 UTC, grunger94 commented on commons-library/src/test/java/com/afh/skytouch/commons/dto/FindAllMessageTest.java
> +        id.setAccessible(true);
Avoid using reflection for unit tests. Investigate a bit about PowerMock's Whitebox.

2018-09-25 15:40 UTC, AFH7233 commented on product-crud/src/test/java/com/afh/skytouch/services/product/queue/producers/FindAllMessageSenderTest.java
> +import static org.junit.Assert.*;
Fixed

2018-09-25 15:41 UTC, AFH7233 commented on commons-library/pom.xml
> -            <version>${lombok.version}</version>
It had a bug related to the naming and then i forgot to brought it back. Fixed now

2018-09-25 15:41 UTC, AFH7233 commented on docker/docker-compose.yml
> +      - "5672:5672"
Changed

2018-09-25 15:42 UTC, AFH7233 commented on commons-library/pom.xml
> +            <groupId>org.jetbrains</groupId>
removed, but I think intelliJ added them.

2018-09-25 15:44 UTC, AFH7233 commented on management-api/src/main/java/com/afh/skytouch/managment/controllers/GenericProductController.java
> +    public static final String PRODUCT_ATRIBUTE_NAME = "product";
They were but I reused them in the test, so I think at least could be package private.

2018-09-25 15:44 UTC, AFH7233 commented on management-api/src/main/java/com/afh/skytouch/managment/controllers/GenericProductController.java
> +    @Value("${managment.service.timeout}")
jejeje yes it was a typo thanks

2018-09-25 15:45 UTC, AFH7233 commented on management-api/src/main/java/com/afh/skytouch/managment/controllers/GenericProductController.java
> +        System.out.println("Checking again: " + id);
Removed

2018-09-25 15:45 UTC, AFH7233 commented on commons-library/src/test/java/com/afh/skytouch/commons/dto/FindAllMessageTest.java
> +        id.setAccessible(true);
Changed to use whitebox

2019-03-04 18:29 UTC, merged